### ISSUE TITLE
Testing POST

### ISSUE THREAD

**Issue by MainShayne233** [elixir-maru/maru#46]
First off I just want to say I absolutely love this framework with all my heart. 

Currently I am using this helper to test my POST requests

```elixir
  use ExUnit.Case
  use Maru.Test, for: DataApi

  def post_and_respond(body, url) do
    build_conn
    |> Plug.Conn.put_req_header("content-type", "application/json")
    |> put_body_or_params(Poison.encode!(body))
    |> post(url)
    |> Map.get(:resp_body)
    |> Poison.decode
  end
```

This is obviously fine, but I imagine there is a better way.

**Comment by falood** [comment]
Thank you for loving maru ❤️ 
You can replace the last two lines with `json_response` which defined at https://github.com/elixir-maru/maru/blob/master/lib/maru/test.ex#L152
And if you test all your endpoint with the same way, just move your helper method as `YouHelperModule.post_and_respond/2` within `test_helper.exs`, and then import the module in all your test files.
I haven't make one by default because I think different people test different things, and a test module could be made very easy.

**Comment by MainShayne233** [comment]
Perfect! Exactly what I was going for :).
