### ISSUE TITLE
Advice on learning maru

### ISSUE THREAD

**Issue by CharlesIrvineKC** [elixir-maru/maru#73]
I'm finding the maru documentation insufficient for a new user like me to get started. I wonder if the author kind of assumes that users will be familiar with Grape and I'm not.

Can anyone suggest any learning material that they think might be helpful?

**Comment by falood** [comment]
Hi @ChuckIrvine
When I want to learn something, I usually build a demo first, and then read the document about what I can do with it, after that I check the examples and unit test for some corner cases and best practices.
Follow this, I write the demo in the [README.md](https://github.com/elixir-maru/maru/blob/master/README.md), the details of every part [here](https://maru.readme.io/), examples [here](https://github.com/elixir-maru/maru_examples) and also a little bit about how maru works with hexdocs.

Maybe I haven't made the docs good, can I have some suggestion from you? What kind of docs do you think is good? What's the best step do you think for learning maru?

Thank you ❤️

**Comment by ChuckIrvine** [comment]
Hi Xiangrong,

Thanks for responding.

Writing documentation can be very time consuming and I understand that you might have other priorities.

I wanted to write my REST API in Elixir because it offers great performance which I think I will eventually need. First I looked at Phoenix. Since I like to start simple it wasn’t for me. Also, its documentation isn't very good for someone that just wants to build a REST API.

After that I started looking at Maru. I’ve used Sinatra/Ruby to build APIs and Maru looked a little like Sinatra so I liked that. However, the documentation wasn’t detailed enough to get me quickly going. For my prototype, I’m going to use Express and switch back over to Elixir when I need it’s performance.

As far as giving you advice on how to extend Maru’s documentation, please don’t try to do that unless it’s something you want to spend time on. After all, you aren't getting paid for it.

If you do want to spend some time on it, I guess you could have a look at the Grape or Express docs and use those as a model. I haven’t used Grape before, but the Express docs are quite good.

Thanks very much for you time.

Regards,
Chuck Irvine

**Comment by falood** [comment]
@ChuckIrvine 
Thank you very much, I'll check more documents of other frameworks even if I don't use the language which build them, and think more about maru docs.

**Comment by jalcine** [comment]
If there's a ticket that has a run-down of things that one could give a guide to, I'm down to help.

We can even leverage Github here and make a 'cookbook' of sorts; expanding the examples repository to have guides explaining how to use them.
